/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aibox.view;

import aibox.*;
import aibox.view.*;
import aibox.utils.Koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author romad
 */
public class Layout extends javax.swing.JFrame {

    Koneksi koneksi = new Koneksi();

    private DefaultTableModel tableModel;

    private void ProdukPrefixID() {
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM produk ORDER BY id DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String NoProduk = r.getString("id").substring(2);
                String PR = "" + (Integer.parseInt(NoProduk) + 1);
                String Nol = "";

                if (PR.length() == 1) {
                    Nol = "000";
                } else if (PR.length() == 2) {
                    Nol = "00";
                } else if (PR.length() == 3) {
                    Nol = "0";
                } else if (PR.length() == 4) {
                    Nol = "";
                }

                ProdukInputID.setText("PR" + Nol + PR);

            } else {
                ProdukInputID.setText("PR0001");
            }
            r.close();
            s.close();
        } catch (Exception e) {
            System.out.println("ProdukPrefixID error");
        }
    }

    public void clear() {
        ProdukInputNama.setText("");
        ProdukInputHarga.setText("");
        ProdukInputStok.setText("");
    }

    public void loadData() {
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        ProdukButtonSimpan.setEnabled(true);
        ProdukButtonEdit.setEnabled(false);
        ProdukButtonBatal.setEnabled(false);
        ProdukButtonHapus.setEnabled(false);

        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM produk";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[5];
                o[0] = r.getString("id");
                o[1] = r.getString("nama");
                o[2] = r.getString("jenis");
                o[3] = r.getString("harga");
                o[4] = r.getString("stok");

                tableModel.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("terjadi kesalahan");
        }
    }

    public Layout() {
        initComponents();
        this.setLocationRelativeTo(null);

        ProdukInputID.setEnabled(false);

        tableModel = new DefaultTableModel();

        ProdukDatatable.setModel(tableModel);

        tableModel.addColumn("ID");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Jenis");
        tableModel.addColumn("Harga");
        tableModel.addColumn("Stok");

        loadData();
        ProdukPrefixID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        LogoText = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        MenuProduk = new javax.swing.JLabel();
        MenuProdukSeparatorBottom = new javax.swing.JSeparator();
        MenuProdukSeparatorTop = new javax.swing.JSeparator();
        MenuTransaksiSeparatorBottom = new javax.swing.JSeparator();
        MenuPelangganSeparatorBottom1 = new javax.swing.JSeparator();
        MenuProduk1 = new javax.swing.JLabel();
        MenuProduk2 = new javax.swing.JLabel();
        Content = new javax.swing.JTabbedPane();
        ManajemenProduk = new javax.swing.JPanel();
        ProdukPanelHeader = new javax.swing.JPanel();
        ProdukPanelHeaderLabel = new javax.swing.JLabel();
        ProdukLabelID = new javax.swing.JLabel();
        ProdukInputID = new javax.swing.JTextField();
        ProdukLabelNama = new javax.swing.JLabel();
        ProdukInputNama = new javax.swing.JTextField();
        ProdukLabelJenis = new javax.swing.JLabel();
        ProdukInputJenis = new javax.swing.JComboBox();
        ProdukLabelHarga = new javax.swing.JLabel();
        ProdukInputHarga = new javax.swing.JTextField();
        ProdukLabelPencarian = new javax.swing.JLabel();
        ProdukInputPencarian = new javax.swing.JTextField();
        ProdukDatatableOverflow = new javax.swing.JScrollPane();
        ProdukDatatable = new javax.swing.JTable();
        ProdukButtonSimpan = new javax.swing.JButton();
        ProdukButtonEdit = new javax.swing.JButton();
        ProdukButtonHapus = new javax.swing.JButton();
        ProdukButtonBatal = new javax.swing.JButton();
        ProdukLabelStok = new javax.swing.JLabel();
        ProdukInputStok = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Body.setBackground(new java.awt.Color(204, 204, 204));

        Sidebar.setBackground(new java.awt.Color(0, 0, 0));

        LogoText.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        LogoText.setForeground(new java.awt.Color(255, 255, 255));
        LogoText.setText("AIBOX");

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibox/img/aibox-logo-white.png"))); // NOI18N
        LogoImg.setText("jLabel2");

        MenuProduk.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        MenuProduk.setForeground(new java.awt.Color(255, 255, 255));
        MenuProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibox/img/ic-transaksi.png"))); // NOI18N
        MenuProduk.setText("  TRANSAKSI");
        MenuProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuProduk1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        MenuProduk1.setForeground(new java.awt.Color(255, 255, 255));
        MenuProduk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibox/img/ic-pelanggan.png"))); // NOI18N
        MenuProduk1.setText("  PELANGGAN");
        MenuProduk1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuProduk2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        MenuProduk2.setForeground(new java.awt.Color(255, 255, 255));
        MenuProduk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibox/img/ic-product.png"))); // NOI18N
        MenuProduk2.setText("  PRODUK");
        MenuProduk2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuProdukSeparatorBottom, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(MenuProdukSeparatorTop)
            .addComponent(MenuTransaksiSeparatorBottom, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPelangganSeparatorBottom1))
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LogoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuProduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuProduk1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuProduk2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LogoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoText)
                .addGap(65, 65, 65)
                .addComponent(MenuProdukSeparatorTop, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(MenuProdukSeparatorBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuTransaksiSeparatorBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuProduk1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuPelangganSeparatorBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Content.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ManajemenProduk.setBackground(new java.awt.Color(241, 241, 241));
        ManajemenProduk.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ProdukPanelHeader.setBackground(new java.awt.Color(0, 0, 0));

        ProdukPanelHeaderLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        ProdukPanelHeaderLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProdukPanelHeaderLabel.setText("MANAJEMEN PRODUK");

        javax.swing.GroupLayout ProdukPanelHeaderLayout = new javax.swing.GroupLayout(ProdukPanelHeader);
        ProdukPanelHeader.setLayout(ProdukPanelHeaderLayout);
        ProdukPanelHeaderLayout.setHorizontalGroup(
            ProdukPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdukPanelHeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ProdukPanelHeaderLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProdukPanelHeaderLayout.setVerticalGroup(
            ProdukPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProdukPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(ProdukPanelHeaderLabel)
                .addGap(19, 19, 19))
        );

        ProdukLabelID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukLabelID.setText("ID");

        ProdukInputID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ProdukLabelNama.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukLabelNama.setText("Nama");

        ProdukInputNama.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ProdukLabelJenis.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukLabelJenis.setText("Kategori");

        ProdukInputJenis.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukInputJenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "iPhone", "iPad", "Macbook", "Lainnya" }));

        ProdukLabelHarga.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukLabelHarga.setText("Harga");

        ProdukInputHarga.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ProdukLabelPencarian.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukLabelPencarian.setText("Pencarian");

        ProdukInputPencarian.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukInputPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ProdukInputPencarianKeyTyped(evt);
            }
        });

        ProdukDatatable.setAutoCreateRowSorter(true);
        ProdukDatatable.setBackground(new java.awt.Color(0, 0, 0));
        ProdukDatatable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukDatatable.setForeground(new java.awt.Color(255, 255, 255));
        ProdukDatatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Kategori", "Harga", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProdukDatatable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProdukDatatable.setRowHeight(30);
        ProdukDatatable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdukDatatableMouseClicked(evt);
            }
        });
        ProdukDatatableOverflow.setViewportView(ProdukDatatable);

        ProdukButtonSimpan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukButtonSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibox/img/ic-simpan.png"))); // NOI18N
        ProdukButtonSimpan.setText(" Simpan");
        ProdukButtonSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProdukButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdukButtonSimpanActionPerformed(evt);
            }
        });

        ProdukButtonEdit.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibox/img/ic-edit.png"))); // NOI18N
        ProdukButtonEdit.setText(" Edit");
        ProdukButtonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProdukButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdukButtonEditActionPerformed(evt);
            }
        });

        ProdukButtonHapus.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukButtonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibox/img/ic-hapus.png"))); // NOI18N
        ProdukButtonHapus.setText(" Hapus");
        ProdukButtonHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProdukButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdukButtonHapusActionPerformed(evt);
            }
        });

        ProdukButtonBatal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukButtonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aibox/img/ic-batal.png"))); // NOI18N
        ProdukButtonBatal.setText(" Batal");
        ProdukButtonBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProdukButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdukButtonBatalActionPerformed(evt);
            }
        });

        ProdukLabelStok.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ProdukLabelStok.setText("Stok");

        ProdukInputStok.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout ManajemenProdukLayout = new javax.swing.GroupLayout(ManajemenProduk);
        ManajemenProduk.setLayout(ManajemenProdukLayout);
        ManajemenProdukLayout.setHorizontalGroup(
            ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProdukPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ManajemenProdukLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManajemenProdukLayout.createSequentialGroup()
                        .addComponent(ProdukButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProdukButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManajemenProdukLayout.createSequentialGroup()
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProdukLabelNama)
                            .addComponent(ProdukLabelID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProdukInputNama, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(ProdukInputID)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManajemenProdukLayout.createSequentialGroup()
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProdukLabelHarga)
                            .addComponent(ProdukLabelJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProdukInputHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(ProdukInputJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(ManajemenProdukLayout.createSequentialGroup()
                        .addComponent(ProdukLabelStok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProdukInputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ManajemenProdukLayout.createSequentialGroup()
                        .addComponent(ProdukDatatableOverflow, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(ManajemenProdukLayout.createSequentialGroup()
                        .addComponent(ProdukLabelPencarian)
                        .addGap(12, 12, 12)
                        .addComponent(ProdukInputPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProdukButtonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProdukButtonHapus)
                        .addContainerGap())))
        );
        ManajemenProdukLayout.setVerticalGroup(
            ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManajemenProdukLayout.createSequentialGroup()
                .addComponent(ProdukPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManajemenProdukLayout.createSequentialGroup()
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProdukInputPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProdukLabelPencarian)
                            .addComponent(ProdukButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProdukButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ProdukDatatableOverflow, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                    .addGroup(ManajemenProdukLayout.createSequentialGroup()
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProdukLabelID)
                            .addComponent(ProdukInputID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProdukInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProdukLabelNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProdukInputJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProdukLabelJenis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProdukInputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProdukLabelHarga))
                        .addGap(18, 18, 18)
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProdukInputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProdukLabelStok))
                        .addGap(37, 37, 37)
                        .addGroup(ManajemenProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProdukButtonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(ProdukButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        Content.addTab("PRODUK", ManajemenProduk);

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BodyLayout.createSequentialGroup()
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Content.getAccessibleContext().setAccessibleName("Content");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProdukInputPencarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProdukInputPencarianKeyTyped
        // TODO add your handling code here:
        DefaultTableModel tabel = new DefaultTableModel();

        tabel.addColumn("ID");
        tabel.addColumn("Nama");
        tabel.addColumn("Jenis");
        tabel.addColumn("Harga");
        tabel.addColumn("Stok");

        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "Select * from produk where nama like '%" + ProdukInputPencarian.getText() + "%'";
            Statement stat = c.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[] {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                });
            }
            ProdukDatatable.setModel(tabel);
            loadData();
        } catch (Exception e) {
            System.out.println("Cari Data Error");
        } finally {}
    }//GEN-LAST:event_ProdukInputPencarianKeyTyped

    private void ProdukDatatableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdukDatatableMouseClicked
        // TODO add your handling code here:
        ProdukButtonSimpan.setEnabled(false);
        ProdukButtonEdit.setEnabled(true);
        ProdukButtonBatal.setEnabled(true);
        ProdukButtonHapus.setEnabled(true);
        int i = ProdukDatatable.getSelectedRow();
        if (i == -1) {
            return;
        }

        String id = (String) tableModel.getValueAt(i, 0);
        ProdukInputID.setText(id);
        String nama = (String) tableModel.getValueAt(i, 1);
        ProdukInputNama.setText(nama);
        String jenis = (String) tableModel.getValueAt(i, 2);
        ProdukInputJenis.setSelectedItem(jenis);
        String harga = (String) tableModel.getValueAt(i, 3);
        ProdukInputHarga.setText(harga);
        String stok = (String) tableModel.getValueAt(i, 4);
        ProdukInputStok.setText(stok);
    }//GEN-LAST:event_ProdukDatatableMouseClicked

    private void ProdukButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdukButtonSimpanActionPerformed
        // TODO add your handling code here:
        String id = ProdukInputID.getText();
        String nama = ProdukInputNama.getText();
        String jenis = (String) ProdukInputJenis.getSelectedItem();
        String harga = ProdukInputHarga.getText();
        String stok = ProdukInputStok.getText();

        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "INSERT INTO produk VALUES (?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.setString(2, nama);
            p.setString(3, jenis);
            p.setString(4, harga);
            p.setString(5, stok);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
        } catch (SQLException e) {
            System.out.println("Terjadi Kesalahan");
        } finally {
            loadData();
            ProdukPrefixID();
            clear();
        }
    }//GEN-LAST:event_ProdukButtonSimpanActionPerformed

    private void ProdukButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdukButtonEditActionPerformed
        // TODO add your handling code here:
        int i = ProdukDatatable.getSelectedRow();
        if (i == -1) {
            return;
        }
        String id = (String) tableModel.getValueAt(i, 0);
        String nama = ProdukInputNama.getText();
        String jenis = (String) ProdukInputJenis.getSelectedItem();
        String harga = ProdukInputHarga.getText();
        String stok = ProdukInputStok.getText();

        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "UPDATE produk SET nama = ?, jenis = ?, harga = ?, stok = ? WHERE id = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama);
            p.setString(2, jenis);
            p.setString(3, harga);
            p.setString(4, stok);
            p.setString(5, id);

            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Terubah");
            ProdukButtonSimpan.setEnabled(true);
            clear();
        } catch (SQLException e) {
            System.out.println("Update Error");
        } finally {
            loadData();
            ProdukPrefixID();
        }
    }//GEN-LAST:event_ProdukButtonEditActionPerformed

    private void ProdukButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdukButtonHapusActionPerformed
        // TODO add your handling code here:
        int i = ProdukDatatable.getSelectedRow();
        if (i == -1) {
            return;
        }

        String id = (String) tableModel.getValueAt(i, 0);

        int question = JOptionPane.showConfirmDialog(null, "Yakin Data Akan Dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (question == JOptionPane.OK_OPTION) {
            try {
                Connection c = Koneksi.getKoneksi();
                String sql = "DELETE FROM produk WHERE id = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "Data Terhapus");
            } catch (SQLException e) {
                System.out.println("Terjadi Kesalahab");
            } finally {
                loadData();
                ProdukPrefixID();
                clear();
            }
        }
        if (question == JOptionPane.CANCEL_OPTION) {}
    }//GEN-LAST:event_ProdukButtonHapusActionPerformed

    private void ProdukButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdukButtonBatalActionPerformed
        // TODO add your handling code here:
        clear();
        loadData();
        ProdukButtonSimpan.setEnabled(true);
        ProdukPrefixID();
    }//GEN-LAST:event_ProdukButtonBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JTabbedPane Content;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JLabel LogoText;
    private javax.swing.JPanel ManajemenProduk;
    private javax.swing.JSeparator MenuPelangganSeparatorBottom1;
    private javax.swing.JLabel MenuProduk;
    private javax.swing.JLabel MenuProduk1;
    private javax.swing.JLabel MenuProduk2;
    private javax.swing.JSeparator MenuProdukSeparatorBottom;
    private javax.swing.JSeparator MenuProdukSeparatorTop;
    private javax.swing.JSeparator MenuTransaksiSeparatorBottom;
    private javax.swing.JButton ProdukButtonBatal;
    private javax.swing.JButton ProdukButtonEdit;
    private javax.swing.JButton ProdukButtonHapus;
    private javax.swing.JButton ProdukButtonSimpan;
    private javax.swing.JTable ProdukDatatable;
    private javax.swing.JScrollPane ProdukDatatableOverflow;
    private javax.swing.JTextField ProdukInputHarga;
    private javax.swing.JTextField ProdukInputID;
    private javax.swing.JComboBox ProdukInputJenis;
    private javax.swing.JTextField ProdukInputNama;
    private javax.swing.JTextField ProdukInputPencarian;
    private javax.swing.JTextField ProdukInputStok;
    private javax.swing.JLabel ProdukLabelHarga;
    private javax.swing.JLabel ProdukLabelID;
    private javax.swing.JLabel ProdukLabelJenis;
    private javax.swing.JLabel ProdukLabelNama;
    private javax.swing.JLabel ProdukLabelPencarian;
    private javax.swing.JLabel ProdukLabelStok;
    private javax.swing.JPanel ProdukPanelHeader;
    private javax.swing.JLabel ProdukPanelHeaderLabel;
    private javax.swing.JPanel Sidebar;
    // End of variables declaration//GEN-END:variables
}